[project]
name = "py-code-act"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "username13121", email = "username12312355@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
py-code-act = "py_code_act:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
